{% set version = "1.5.0" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-statcheck
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/statcheck_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/statcheck/statcheck_{{ version }}.tar.gz
  sha256: a7d9f97adfd2409e0facd9bc569ddd3851200e2275b1d089086816179101593f

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic

requirements:
  build:
    - {{ posix }}zip  # [win]

  host:
    - r-base
    - r-ggplot2
    - r-plyr
    - r-rlang
    - r-rmarkdown
    - r-stringi

  run:
    - r-base
    - r-ggplot2
    - r-plyr
    - r-rlang
    - r-rmarkdown
    - r-stringi

test:
  commands:
    - $R -e "library('statcheck')"  # [not win]
    - "\"%R%\" -e \"library('statcheck')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=statcheck
  license: GPL-2.0-only
  summary: Extract statistics from articles and recompute p values.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: statcheck
# Type: Package
# Title: Extract Statistics from Articles and Recompute p Values
# Version: 1.3.0
# Date: 2018-05-04
# Author: Sacha Epskamp <mail@sachaepskamp.com> & Michele B. Nuijten <m.b.nuijten@uvt.nl>
# Maintainer: Michele B. Nuijten <m.b.nuijten@uvt.nl>
# Depends: R (>= 2.14.2)
# Imports: plyr, ggplot2, rmarkdown
# Description: Extract statistics from articles and recompute p values.
# License: GPL-2
# LazyLoad: yes
# ByteCompile: yes
# NeedsCompilation: no
# Packaged: 2018-05-04 09:49:38 UTC; mnuijten
# Repository: CRAN
# Date/Publication: 2018-05-04 11:03:58 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
